name: aave_sdk
description: Aave sdk for dart.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  web3dart: ^2.0.0-dev
  pedantic: ^1.8.0
  http: ^0.12.0+4
  web_socket_channel: ^1.1.0
  erc20:
    path: ../erc20

dev_dependencies:
  test: ^1.6.0
